In [1]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.79522971, -0.56213239,  0.42207287],
       [ 1.3706689 ,  0.32248426, -0.67331614]])

In [2]:
data * 10

array([[-7.95229713, -5.62132389,  4.22072873],
       [13.70668895,  3.22484263, -6.73316139]])

In [3]:
data

array([[-0.79522971, -0.56213239,  0.42207287],
       [ 1.3706689 ,  0.32248426, -0.67331614]])

In [4]:
data + data

array([[-1.59045943, -1.12426478,  0.84414575],
       [ 2.74133779,  0.64496853, -1.34663228]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

In [7]:
# Create an array

my_list = [1, 2, 3, 4]
list_array = np.array(my_list)
list_array

array([1, 2, 3, 4])

In [9]:
nested_list = [[1, 2, 3, 5], [1, 2, 3, 4]]
nested_array = np.array(nested_list)
nested_array

array([[1, 2, 3, 5],
       [1, 2, 3, 4]])

In [10]:
nested_array.ndim

2

In [13]:
nested_array.shape

(2, 4)

In [16]:
np.arange(3)

array([0, 1, 2])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.empty(4)

array([1., 1., 1., 1.])