## 1. Import numpy as np and see the version 

In [2]:
import numpy as np
print(np.__version__)

1.16.2


## 2. Create a 1D array of numbers from 0 to 9

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a 3×3 numpy array of all True’s

In [4]:
ver1 = np.full((3,3), True, dtype=bool)
ver1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
ver2 = np.ones((3,3), dtype=bool)
ver2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. Extract all odd numbers from arr

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## 5. Replace all odd numbers in arr with -1

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[arr % 2 == 1] = -1

In [10]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. Replace all odd numbers in arr with -1 without changing arr

In [11]:
arr = np.arange(10)
out = arr.copy()
out[out % 2 == 1] = -1
print(out)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Suggested Solution

In [12]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 7. Reshape an Array: Convert a 1D array to a 2D array with 2 rows

In [13]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#arr.reshape(2,5)

In [15]:
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. Stack arrays a and b vertically

In [16]:
# Inputs
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
# Desired Output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [18]:
# Method 1:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# Method 2:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. Stack the arrays a and b horizontally.

In [21]:
# Inputs
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [22]:
# Desired Outputs
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [23]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [24]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [25]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10.Create the following pattern without hardcoding. Use only numpy functions and the below input array a. 

In [26]:
# Inputs
a = np.array([1,2,3])

In [27]:
# Desired Outputs
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. Get the common items between a and b

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [30]:
np.intersect1d(a,b)

array([2, 4])

## 12. From array a remove all items present in array b

In [37]:
# Inputs
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Desired Output
# array([1,2,3,4])

In [38]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

## 13. Get the positions where elements of a and b match 

In [41]:
# Inputs
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output
#> (array([1, 3, 5, 7]),)

In [44]:
np.where(np.in1d(a,b))[0]

array([1, 3, 5, 7], dtype=int64)

np.in1d(A, B) returns a boolean array indicating whether each value of A is found in B. np.where returns the indices of the True values.