## 1. Import numpy as np and see the version 

In [1]:
import numpy as np
print(np.__version__)

1.16.2


## 2. Create a 1D array of numbers from 0 to 9

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3. Create a 3×3 numpy array of all True’s

In [3]:
ver1 = np.full((3,3), True, dtype=bool)
ver1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
ver2 = np.ones((3,3), dtype=bool)
ver2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## 4. Extract all odd numbers from arr

In [5]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## 5. Replace all odd numbers in arr with -1

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[arr % 2 == 1] = -1

In [9]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 6. Replace all odd numbers in arr with -1 without changing arr

In [10]:
arr = np.arange(10)
out = arr.copy()
out[out % 2 == 1] = -1
print(out)
arr

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Suggested Solution

In [11]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## 7. Reshape an Array: Convert a 1D array to a 2D array with 2 rows

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#arr.reshape(2,5)

In [14]:
arr.reshape(2, -1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 8. Stack arrays a and b vertically

In [15]:
# Inputs
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [16]:
# Desired Output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [17]:
# Method 1:
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# Method 2:
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
# Method 3:
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## 9. Stack the arrays a and b horizontally.

In [20]:
# Inputs
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [21]:
# Desired Outputs
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [22]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [23]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [24]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## 10.Create the following pattern without hardcoding. Use only numpy functions and the below input array a. 

In [25]:
# Inputs
a = np.array([1,2,3])

In [26]:
# Desired Outputs
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

## 11. Get the common items between a and b

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [28]:
np.intersect1d(a,b)

array([2, 4])

## 12. From array a remove all items present in array b

In [29]:
# Inputs
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Desired Output
# array([1,2,3,4])

In [30]:
np.setdiff1d(a, b)

array([1, 2, 3, 4])

## 13. Get the positions where elements of a and b match 

In [31]:
# Inputs
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Desired Output
#> (array([1, 3, 5, 7]),)

In [32]:
np.where(np.in1d(a,b))[0]

array([1, 3, 5, 7], dtype=int64)

np.in1d(A, B) returns a boolean array indicating whether each value of A is found in B. np.where returns the indices of the True values.

## 14. Get all items between 5 and 10 from a

In [33]:
# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])
# Desired Output
# (array([6, 9, 10]),)

In [44]:
a2 = [i for i in a if (i>=5 and i<=10)] # List Comprehension

In [45]:
a2

[6, 9, 10]

In [48]:
# Method 1: np.where
index = np.where((a >= 5) & (a <= 10))
a[index]
#index

array([ 6,  9, 10])

In [49]:
# Method 2
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [50]:
# Method 3
a[(a >= 5) & (a <= 10)]

array([ 6,  9, 10])

## 15. Convert the function maxx that works on two scalars, to work on two arrays.

In [51]:
# Input
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [53]:
# Desired Output
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

In [ ]:
def pair_max(a, b):
    